### ISSUE TITLE
Where to download the test files

### ISSUE THREAD

**Issue by tzhang004** [oldguyeric/TCRcloud#1]
HI! I tried to run commands with the files AIRR_repertoire_file.json and AIRR_rearrangements_file.tsv, but can't find them even after I downloaded the test data files. I am writing to ask where to find these AIRR files? Thank you!

**Comment by eriicdesousa** [comment]
The command "testdata" downloads a file called testdata.airr.json. Then you have use the command "download" to get a file called testdata.airr.rearrangements.tsv. Then you can test the tool

**Comment by eriicdesousa** [comment]
Version 1.3.0 changes the names of the test files making it easier to understand. I'm going to mark this issue as closed.
